#!/usr/bin/env bash
#MISE description="Deploy to Cloudflare Workers."
#MISE hide=true
#MISE dir="worker"
#MISE depends=["worker:build"]

#USAGE flag "--preview" default="false" help="Upload a new version without deploying it."

set -euo pipefail

# run dependency tasks if directly called in workers build environment
if [[ -z ${MISE_TASK_NAME:-} ]]; then
	script_dir=$(dirname "${BASH_SOURCE[0]}")
	# shellcheck source=worker/tasks/worker/build
	source "${script_dir}/build"
fi

wrangler_cmd="deploy"

# use $1 if usage_preview is not set to support direct call in workers build environment
if [[ -z ${usage_preview:-} ]]; then
	if [[ ${1:-} == '--preview' ]]; then
		usage_preview=true
	else
		usage_preview=false
	fi
fi

if [[ ${usage_preview} == 'true' ]]; then
	wrangler_cmd="versions upload"
	# tag length is limited to 25 characters
	short_sha=$(git rev-parse --short HEAD)
	message=$(git log --format=%B --max-count=1 "${short_sha}" | head --lines=1 | sed 's/"/\\"/g')
fi

set -x
# shellcheck disable=SC2086 # avoid quoting wrangler_cmd and vars
bun run wrangler ${wrangler_cmd} \
	${short_sha:+--tag "${short_sha}"} \
	${message:+--message "${message}"}
