#!/usr/bin/env bash
#MISE description="Deploy to Cloudflare Workers."
#MISE hide=true
#MISE dir="worker"
#MISE depends=["worker:build"]

#USAGE flag "--preview" default="false" help="Upload a new version without deploying it."

set -euo pipefail

# tag length is limited to 25 characters
short_sha=$(git rev-parse --short HEAD)
message=$(git log -1 --format=%s HEAD)

set -x
bun run wrangler versions upload --tag "${short_sha}" --message "${message}"
set +x

if [[ ${usage_preview} == 'true' ]]; then
	exit 0
fi

versions=$(bun run wrangler versions list --json)
id=$(echo "${versions}" | jq --raw-output ".[] | select(.annotations.\"workers/tag\" == \"${short_sha}\") | .id")

set -x
bun run wrangler versions deploy --yes "${id}"
set +x
