#!/usr/bin/env bash
# mise hide=true

# do not use dir="worker" as it will cause error if the script is run from worker directory

set -euo pipefail

# support only running from the root directory or worker directory
# manual `mise run` is from the root directory, and calling from other `mise run` is from the worker directory
cwd=$(pwd)
if [[ $(basename "${cwd}") != "worker" ]]; then
	cd worker
fi

# cspell:ignore workerd
# extract the compatibility_date from the compatibility_workerd_version in wrangler.toml
# ref: https://github.com/cloudflare/workers-sdk/blob/81dfb1746a2b2a17c06f809b2da9f937810ca701/packages/create-cloudflare/src/helpers/compatDate.ts#L27-L28
compatibility_workerd_version=$(grep 'compatibility_workerd_version' wrangler.toml)
echo "${compatibility_workerd_version}" | sed --regexp-extended 's/.*[0-9]+\.([0-9]{4})([0-9]{2})([0-9]{2})\.[0-9]+.*/\1-\2-\3/'
