# ref: https://mise.jdx.dev/configuration.html
#:schema https://mise.jdx.dev/schema/mise.json

min_version = "2026.4.18"

[vars]
PS_SCRIPT_ANALYZER_VERSION = "1.25.0"

[tools]
# core runtimes
bun = "latest"
node = "latest"

# linter/formatter tools
oxlint = "latest"
oxfmt = "latest"
actionlint = "latest"
ghalint = "latest"
pinact = "latest"
zizmor = "latest"
taplo = "latest"
markdownlint-cli2 = "latest"
shfmt = "latest"
shellcheck = "latest"
yamlfmt = "latest"
yamllint = "latest"
lychee = "latest"
typos = "latest"
hadolint = "latest"

# npm packages
"npm:ignore-sync" = "latest"
"npm:jschema-validator" = "latest"

# other tools
# required for pipx backend
uv = "latest"
jc = "latest"
powershell = "latest"
copilot = "latest"

[settings]
experimental = true

[settings.npm]
package_manager = "bun"

[task_config]
includes = ["tasks.toml", "tasks", "worker/tasks.toml", "worker/tasks"]

[hooks]
postinstall = """
{% if env.CI is undefined %}
  mise run buni ::: install:ps-script-analyzer
{% endif %}
"""
