# ref: https://mise.jdx.dev/tasks/
#:schema https://mise.jdx.dev/schema/mise-task.json

[check]
run = "hk {% if env.CI is defined %}--profile ci {% endif %}{% if env.SCHEDULED_LINT is defined and env.SCHEDULED_LINT == 'true' %}--profile scheduled {% endif %}{% if env.LINT is defined %}check{% else %}fix{% endif %} --all --no-progress --no-fail-fast"
env.GH_TOKEN = "{% if env.GITHUB_TOKEN is defined %}{{ env.GITHUB_TOKEN }}{% endif %}"
description = "Run hk linters and formatters."

["install:ps-script-analyzer"]
shell = "pwsh -Command"
# Force is required to bypass untrusted repository confirmation
# ref: https://github.com/PowerShell/PowerShellGetv2/issues/461
run = """
$RequiredVersion = '{{ vars.PS_SCRIPT_ANALYZER_VERSION }}'

if (Get-Module -ListAvailable -FullyQualifiedName @{ ModuleName = 'PSScriptAnalyzer'; RequiredVersion = $RequiredVersion }) {
  exit 0
}

Install-Module -Name PSScriptAnalyzer -RequiredVersion $RequiredVersion -Force
"""
