# ref: https://github.com/crate-ci/typos/blob/master/docs/reference.md

[files]
ignore-hidden = false
extend-exclude = [".git"]

[default.extend-words]
# abbreviation of fingerprint
fpr = "fpr"
# typo but used in Biome
# ref: https://biomejs.dev/linter/rules/no-inferrable-types/
inferrable = "inferrable"
