set -g mouse on

set -g status-left-length 80
set -g status-left '#[bold]#{b:pane_current_path}#[default] #(git -C "#{pane_current_path}" branch --show-current 2>/dev/null | sed "s/^/[/" | sed "s/$/]/") '
set -g status-right ''
