#!/usr/bin/env bash
#MISE description="Print variables for wrangler."
#MISE hide=true
#MISE dir="worker"

set -euo pipefail

remote_info=$(git remote show origin)
# in cloudflare workers builds, the url is in the format `https://*****@github.com//owner/repo`
# not sure why there are two slashes, so use `+` to match one or more slashes
# use sed because grep doesn't support lookbehind assertions if the pattern is not fixed width
repo_name=$(echo "${remote_info}" | sed --quiet --regexp-extended 's/.*Fetch URL:.*github.com\/+([^/.]+\/[^/.]+).*/\1/p')
default_branch=$(echo "${remote_info}" | grep --only-matching --perl-regexp '(?<=HEAD branch: ).+')

echo -n "REPO_NAME:${repo_name} DEFAULT_BRANCH:${default_branch}"
