#!/usr/bin/env bash
#MISE description="Generate wrangler arguments for compatibility date and variables"
#MISE hide=true
#MISE dir="worker"
#MISE depends=["buni:worker:silent"]

set -euo pipefail

# cspell:ignore workerd
# use NO_COLOR=1 to avoid ANSI color codes in the output
# bun doesn't support json output for `pm ls`
# ref: https://github.com/oven-sh/bun/issues/8283
compat_date=$(NO_COLOR=1 bun pm ls --all |
	grep --only-matching --perl-regexp '(?<=workerd@)[\d.]+' |
	# use the oldest version of workerd if multiple versions are installed
	sort --version-sort |
	head --lines=1 |
	# extract the date part from the workerd version
	# ref: https://github.com/cloudflare/workers-sdk/blob/81dfb1746a2b2a17c06f809b2da9f937810ca701/packages/create-cloudflare/src/helpers/compatDate.ts#L27-L28
	sed --regexp-extended 's/.*[0-9]+\.([0-9]{4})([0-9]{2})([0-9]{2})\.[0-9]+.*/\1-\2-\3/')

remote_info=$(git remote show origin)
# in cloudflare workers builds, the url is in the format `https://*****@github.com/owner/repo`
# use sed because grep doesn't support lookbehind assertions if the pattern is not fixed width
repo_name=$(echo "${remote_info}" | sed --quiet --regexp-extended 's/.*Fetch URL:.*github.com\/([^/.]+\/[^/.]+).*/\1/p')
default_branch=$(echo "${remote_info}" | grep --only-matching --perl-regexp '(?<=HEAD branch: ).+')

echo "--compatibility-date ${compat_date} --var REPO_NAME:${repo_name} DEFAULT_BRANCH:${default_branch}"
