#:schema https://pitchfork.jdx.dev/schema.json
#:tombi schema.strict = false

[settings]
general.mise = true
web.auto_start = true
supervisor.user = "risu"

[settings.proxy]
enable = true

[namespaces.biwa]
dir = "/home/risu/.ghr/github.com/risu729/biwa"

[slugs]
biwa = { namespace = "biwa", daemon = "docs" }

[daemons]
