#!/usr/bin/env bash
#MISE description="Outputs mise tasks to GITHUB_OUTPUT."
#MISE hide=true

set -euo pipefail

tasks=$(mise tasks ls --json)

output=$(echo "${tasks}" | jq --raw-output --compact-output \
	'map(select(.name | test("^check:[^:]+$"))
		| {
			name: (.name | sub("^.+:" ; "")),
			task: .name,
			require_gh_token: any(.env[]; test("env\\.GITHUB_TOKEN")) | tostring,
			cache_path: (.env["CACHE_PATH"] // ""),
		}
	)')

echo "${output}" | jq

# shellcheck disable=SC2154 # environment variable should be provided
echo "${output}" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >>"${GITHUB_OUTPUT}"
