# ref: https://mise.jdx.dev/tasks/
#:schema https://mise.jdx.dev/schema/mise-task.json

["check:tsc:worker"]
depends = ["check:tsc:worker:*"]
description = "Run TypeScript compiler to check types in the worker directory."

["check:tsc:worker:base"]
depends = ["buni:worker"]
run = "bun run tsc --project tsconfig.base.json {% if env.CI is defined %}--incremental false{% endif %}"
dir = "worker"
description = "Run TypeScript compiler to check types in the worker directory (base)."

["check:tsc:worker:src"]
depends = ["worker:generate:types"]
run = "bun run tsc --project tsconfig.src.json {% if env.CI is defined %}--incremental false{% endif %}"
dir = "worker"
description = "Run TypeScript compiler to check types in the worker directory (src)."

["check:tsc:worker:test"]
depends = ["worker:generate:types"]
run = "bun run tsc --project tsconfig.test.json {% if env.CI is defined %}--incremental false{% endif %}"
dir = "worker"
description = "Run TypeScript compiler to check types in the worker directory (test)."

["worker:dev"]
depends = ["worker:generate:types"]
dir = "worker"
run = "bun run vite dev"
description = "Start a local development server for the worker."

["worker:preview"]
depends = ["worker:build"]
dir = "worker"
run = "bun run vite preview"
description = "Preview the built worker."

["worker:test"]
depends = ["worker:generate:types"]
run = "bun run vitest {% if env.CI is undefined %}watch --ui{% else %}run{% endif %}"
dir = "worker"
description = "Run tests for the worker."

["buni:worker"]
run = "bun install --frozen-lockfile"
dir = "worker"
hide = true
description = "Install Bun dependencies in the worker directory."

["worker:generate:types"]
depends = ["buni:worker"]
run = "bun run wrangler types src/worker-configuration.d.ts"
dir = "worker"
hide = true
description = "Generate types of Cloudflare Worker runtimes."
