# ref: https://mise.jdx.dev/tasks/

["worker:dev"]
extends = "worker:runtime"
run = "bun run vite dev"
description = "Start a local development server for the worker."

["worker:preview"]
extends = "worker"
depends = ["worker:build"]
run = "bun run vite preview"
description = "Preview the built worker."

["worker:test"]
extends = "worker:runtime"
run = "bun run vitest run"
description = "Run Worker tests once."

["worker:test:watch"]
extends = "worker:runtime"
run = "bun run vitest watch --ui"
description = "Watch Worker tests with the Vitest UI."

["worker:generate:types"]
extends = "worker"
run = "bun run wrangler types src/worker-configuration.d.ts"
hide = true
description = "Generate types of Cloudflare Worker runtimes."
