# ref: https://mise.jdx.dev/tasks/
#:schema https://mise.jdx.dev/schema/mise-task.json

["worker:dev"]
depends = ["worker:generate:types"]
dir = "worker"
run = "bun run vite dev"
description = "Start a local development server for the worker."

["worker:preview"]
depends = ["worker:build"]
dir = "worker"
run = "bun run vite preview"
description = "Preview the built worker."

["worker:test"]
depends = ["worker:generate:types"]
run = "bun run vitest {% if env.CI is undefined %}watch --ui{% else %}run{% endif %}"
dir = "worker"
description = "Run tests for the worker."

["worker:generate:types"]
run = "bun run wrangler types src/worker-configuration.d.ts"
dir = "worker"
hide = true
description = "Generate types of Cloudflare Worker runtimes."
