# ref: https://developers.cloudflare.com/workers/wrangler/configuration
#:schema node_modules/wrangler/config-schema.json

name = "dotfiles-worker"
main = "src/index.ts"
minify = true

# cspell:ignore workerd
# set compatibility_date from workerd version
# compatibility_workerd_version = "1.20241018.1"

# required to use vitest
# ref: https://developers.cloudflare.com/workers/testing/vitest-integration/configuration/#workerspooloptions
compatibility_flags = ["nodejs_compat"]

# disable *.worker.dev domain
workers_dev = false

send_metrics = true

[route]
pattern = "dot.risunosu.com"
custom_domain = true

[placement]
mode = "smart"
