#!/usr/bin/env bash
#MISE hide=true
#MISE dir="worker"
#MISE depends=["buni:worker:silent"]

set -euo pipefail

# cspell:ignore workerd
# use NO_COLOR=1 to avoid ANSI color codes in the output
# bun doesn't support json output for `pm ls`
# ref: https://github.com/oven-sh/bun/issues/8283
workerd_version=$(NO_COLOR=1 bun pm ls --all | sed --quiet --regexp-extended 's/.*workerd@(.+)/\1/p')
if [[ ${workerd_version} == *$'\n'* ]]; then
	echo "Multiple versions of workerd are found: ${workerd_version}" >&2
	exit 1
fi
# extract the date part from the workerd version
# ref: https://github.com/cloudflare/workers-sdk/blob/81dfb1746a2b2a17c06f809b2da9f937810ca701/packages/create-cloudflare/src/helpers/compatDate.ts#L27-L28
echo "${workerd_version}" | sed --regexp-extended 's/.*[0-9]+\.([0-9]{4})([0-9]{2})([0-9]{2})\.[0-9]+.*/\1-\2-\3/'
