#!/usr/bin/env bash
#MISE hide=true

# do not use dir="worker" as it will cause error if the script is run from worker directory

set -euo pipefail

# support only running from the root directory or worker directory
# manual `mise run` is from the root directory, and calling from other `mise run` is from the worker directory
cwd=$(pwd)
if [[ $(basename "${cwd}") != "worker" ]]; then
	cd worker
fi

# cspell:ignore workerd
# use NO_COLOR=1 to avoid ANSI color codes in the output
# bun doesn't support json output for `pm ls`
# ref: https://github.com/oven-sh/bun/issues/8283
workerd_version=$(NO_COLOR=1 bun pm ls --all | sed --quiet --regexp-extended 's/.*workerd@(.+)/\1/p')
if [[ ${workerd_version} == *$'\n'* ]]; then
	echo "Multiple versions of workerd are found: ${workerd_version}" >&2
	exit 1
fi
# extract the date part from the workerd version
# ref: https://github.com/cloudflare/workers-sdk/blob/81dfb1746a2b2a17c06f809b2da9f937810ca701/packages/create-cloudflare/src/helpers/compatDate.ts#L27-L28
echo "${workerd_version}" | sed --regexp-extended 's/.*[0-9]+\.([0-9]{4})([0-9]{2})([0-9]{2})\.[0-9]+.*/\1-\2-\3/'
