#!/usr/bin/env bash
#MISE hide=true
#MISE dir="worker"

set -euo pipefail

repo_data=$(gh repo view --json owner,name,defaultBranchRef)
owner=$(echo "${repo_data}" | jq --raw-output '.owner.login')
repo=$(echo "${repo_data}" | jq -r '.name')
default_branch=$(echo "${repo_data}" | jq -r '.defaultBranchRef.name')

echo "REPO_OWNER=${owner}
REPO_NAME=${repo}
DEFAULT_BRANCH=${default_branch}" >.dev.vars
