# ref: https://mise.jdx.dev/configuration.html#global-config-config-mise-config-toml
#:schema https://mise.jdx.dev/schema/mise.json

[env]
RUSTC_WRAPPER = "sccache"
# disable bat paging
BAT_PAGING = "never"
_.path = ["~/.local/bin"]

[tools]
# language tools
node = "latest"
bun = "latest"
aube = "1.9.0" # 1.9.1+ missing GitHub attestations on linux-x64 (mise lock fails)
npm = "latest"
# Don't use the vfox plugin; it doesn't support lockfiles
"aqua:yarn" = "latest"
pnpm = "latest"
java = "latest"
gradle = "latest"
rust = "latest"
python = "latest"
go = "latest"

# mise requirements
cargo-binstall = "latest"
uv = "latest"
# for completion
usage = "latest"
watchexec = "latest"

# cli tools
jq = "latest"
yq = "latest"
github-cli = "latest"
"github:seachicken/gh-poi" = { version = "latest", bin = "gh-poi" }
"aqua:siketyan/ghr" = { version = "latest", prerelease = true }
jc = "latest"
delta = "latest"
ripgrep = "latest"
eza = "latest"
bat = "latest"
fd = "latest"
zoxide = "latest"
btop = "1.4.7"
xh = "latest"
jd = "latest"
sd = "latest"
kubecolor = "latest"
kubectl = "latest"
kubectx = "latest"
kubeseal = "latest"
mitmproxy = "latest"
doggo = "latest"
pitchfork = "latest"
miller = "latest"
glow = "latest"
"github:garden-rs/garden" = "latest"
"pipx:markitdown" = { version = "latest", extras = "all" }
"npm:resend-cli" = "latest"

# ai agents
codex = "latest"
"npm:@ccusage/codex" = "latest"
claude = "latest"
gemini-cli = "latest"
copilot = "latest"

# linter/formatter tools
hk = "latest"
biome = "latest"
oxlint = "latest"
oxfmt = "latest"
actionlint = "latest"
ghalint = "latest"
pinact = "latest"
zizmor = "latest"
taplo = "latest"
prettier = "latest"
shfmt = "latest"
shellcheck = "latest"
yamlfmt = "latest"
yamllint = "latest"
lychee = "latest"
typos = "latest"
hadolint = "latest"

# uni tools
numbat = "latest"
typst = "latest"

# mise development
aqua = "2.58.0" # 2.58.1+ missing GitHub attestations on linux-x64 (mise lock fails)
pipx = "latest"
sccache = "latest"

[settings]
pin = true
experimental = true

[settings.npm]
package_manager = "aube"

[settings.python]
# disable python-build
compile = false

[task_config]
includes = [".config/mise/tasks"]

[shell_alias]
clip = "clip.exe"
m = "mise"
mx = "mise x"
c = "mise run codex-tmux"
l = "eza --all --long --git"
k = "kubecolor"
aptup = "sudo apt update && sudo apt upgrade -y"
cux = "ccusage-codex"
