name: Delete Action Cache

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions: {}

jobs:
  delete-cache:
    name: Delete Action Cache
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      actions: write # for delete cache

    steps:
      - name: Delete Action Cache
        # cspell:ignore toshimaru
        uses: toshimaru/delete-action-cache@ab45c03c4f82162f880096a984a1fe1e7775a292 # v1.0.1
        with:
          limit: 1000

  actions-timeline:
    name: Generate Actions Timeline
    needs:
      - delete-cache
    if: ${{ !cancelled() }}

    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      actions: read # for actions-timeline

    steps:
      - name: actions-timeline
        # cspell:ignore kesin
        uses: Kesin11/actions-timeline@54d513e0b5ff1158f1cf8321108d666a5a6c1fca # v2.2.5
