name: Merge Gatekeeper

# required to use required status checks with paths filters
# ref: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  merge-gatekeeper:
    name: Merge Gatekeeper
    runs-on: ubuntu-24.04
    # set the longest timeout of all jobs
    timeout-minutes: 30
    permissions:
      checks: read
      statuses: read

    steps:
      - name: Merge Gatekeeper
        # cspell:ignore upsidr
        uses: upsidr/merge-gatekeeper@09af7a82c1666d0e64d2bd8c01797a0bcfd3bb5d # v1.2.1
        with:
          token: ${{ github.token }}
          ignored: Generate Actions Timeline, Merge Gatekeeper
          # use timeout-minutes instead of timeout
          timeout: 3600

  actions-timeline:
    name: Generate Actions Timeline
    needs:
      - merge-gatekeeper
    if: ${{ !cancelled() }}

    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      actions: read # for actions-timeline

    steps:
      - name: actions-timeline
        # cspell:ignore kesin
        uses: Kesin11/actions-timeline@a7eaabf426cdae26c3582c3fa674b897170dec8f # v2.2.4
